language: swift
osx_image: xcode10.1
script:
    - xcodebuild clean test -project TemplateTest.xcodeproj -scheme TemplateTest -destination "platform=iOS Simulator,name=iPhone X,OS=12.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet